import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ViewTransitions } from 'next-view-transitions';
import NavLogo from "@/components/Common/NavLogo";
import SmoothScroll from "./SmoothScroll";
import MobileTest from "./MobileTest";
import ContactWrapper from "@/components/ContactCTA/ContactWrapper";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body>
          <SmoothScroll>
            <NavLogo />
            <MobileTest />
            <ContactWrapper />
            {children}
          </SmoothScroll>
        </body>
      </html>
    </ViewTransitions>
  );
}
